# Generated by Django 5.0.4 on 2024-04-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Краткое описание бага')),
                ('description', models.TextField(verbose_name='Полное описание бага')),
                ('status', models.CharField(choices=[('New', 'Новая'), ('In Progress', 'В работе'), ('Completed', 'Завершена')], default='New', max_length=20, verbose_name='Статус бага')),
                ('priority', models.IntegerField(choices=[(1, 'Очень низкий'), (2, 'Низкий'), (3, 'Средний'), (4, 'Высокий'), (5, 'Очень высокий')], default=3, verbose_name='Приоритет бага')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего обновления записи')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project', verbose_name='Проект')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task', verbose_name='Задача')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название запроса на новую функцию')),
                ('description', models.TextField(verbose_name='Описание запроса')),
                ('status', models.CharField(choices=[('Pending', 'Рассмотрение'), ('Accepted', 'Принято'), ('Rejected', 'Отклонено')], default='Pending', max_length=20, verbose_name='Статус запроса')),
                ('priority', models.CharField(choices=[('Low', 'Низкий'), ('Medium', 'Средний'), ('High', 'Высокий')], default='Medium', max_length=10, verbose_name='Приоритет запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания запроса')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего обновления запроса')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project', verbose_name='Проект')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task', verbose_name='Задача')),
            ],
        ),
    ]
